"""Provider-neutral P05 opportunity contracts."""

from core.opportunity.opportunity_candidate import (
    OpportunityCandidate,
    OpportunityCandidateInput,
    OpportunityCandidateResult,
    OpportunityCandidateState,
    OpportunityCandidateStatus,
    OpportunityUpstreamKind,
    OpportunityUpstreamReference,
    P05_T01_CONTRACT_VERSION,
    build_opportunity_candidate,
    build_opportunity_candidate_result,
    create_opportunity_candidate,
    create_opportunity_candidate_result,
)
from core.opportunity.opportunity_normalization import (
    NormalizedOpportunityCandidate,
    OpportunityCandidateNormalization,
    P05_T02_CONTRACT_VERSION,
    normalize_candidate,
    normalize_opportunity_candidate,
)
from core.opportunity.opportunity_risk import (
    CandidateRiskEvaluation,
    CandidateRiskFlag,
    CandidateViabilityStatus,
    HardRiskEvaluation,
    P05_T03_CONTRACT_VERSION,
    P05_T03_EVALUATOR_VERSION,
    evaluate_candidate_risk,
    evaluate_hard_risks,
)

__all__ = [
    "OpportunityCandidate",
    "OpportunityCandidateInput",
    "OpportunityCandidateResult",
    "OpportunityCandidateState",
    "OpportunityCandidateStatus",
    "OpportunityUpstreamKind",
    "OpportunityUpstreamReference",
    "P05_T01_CONTRACT_VERSION",
    "build_opportunity_candidate",
    "build_opportunity_candidate_result",
    "create_opportunity_candidate",
    "create_opportunity_candidate_result",
    "NormalizedOpportunityCandidate",
    "OpportunityCandidateNormalization",
    "P05_T02_CONTRACT_VERSION",
    "normalize_candidate",
    "normalize_opportunity_candidate",
    "CandidateRiskEvaluation",
    "CandidateRiskFlag",
    "CandidateViabilityStatus",
    "HardRiskEvaluation",
    "P05_T03_CONTRACT_VERSION",
    "P05_T03_EVALUATOR_VERSION",
    "evaluate_candidate_risk",
    "evaluate_hard_risks",
]